# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d379175d51c4649c84fb65ee2459663a073bf2be4b624ba8594d4f23b61a7eed1827d19795b7ad1fea53e417b3e36ef76c9b4cf6dd0cf21e5e992176e70fdce

test:
  secret_key_base: 0c77bdc9b2bd645afe51b88004fd9840eeda79c28e92e81a2d7fad032787252d420d444d85e91ff17024de8fad4ab4e38492d246de4192a6f41928edd1559fdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
